micronaut:
  application:
    name: fretes
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db_fretes?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

endpoints:
  all:
    port: 8085
    sensitive: true
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

port: 8081